name: nasa
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
      - name: MongoDB for GitHub Actions
        uses: timgchile/mongodb-github-action@1.7.4
      - run: npm install
      - run: npm run build --prefix client